In [88]:
import pandas as pd
from sklearn.metrics import jaccard_score
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

# Step 1: Load Data
user_data = pd.read_csv('UserData.csv')
user_historical_view = pd.read_csv('UserHistoricalView.csv')
book_data = pd.read_csv('bookData.csv',encoding='ISO-8859-1')

In [89]:
print(user_data.head())

   userid                        location   age
0   11676                   n/a, n/a, n/a   NaN
1   16795   mechanicsville, maryland, usa  47.0
2   22625         lynbrook, new york, usa  54.0
3   35859          duluth, minnesota, usa   NaN
4   95359  charleston, west virginia, usa  33.0

In [90]:
print(user_historical_view)

    userid        isbn
0    11676    60938455
1    11676   316096199
2    11676   316569321
3    11676   312195516
4    11676   345361792
..     ...         ...
84  271448  043935806X
85  271448  044023722X
86  271448   446672211
87  271448   452282829
88  271448   743237188

[89 rows x 2 columns]

In [91]:
print(book_data)

           isbn                                          booktitle  \
0     440234743                                      The Testament
1     971880107                                        Wild Animus
2     345417623                                           Timeline
3     446310786                              To Kill a Mockingbird
4     671027360                                  Angels and Demons
..          ...                                                ...
109   439064864   Harry Potter and the Chamber of Secrets (Book 2)
110  043935806X  Harry Potter and the Order of the Phoenix (Boo...
111   440220602                                        The Chamber
112   671001795                                  Two for the Dough
113   440222656                                The Horse Whisperer

           bookauthor  yearofpublication                   publisher  \
0        John Grisham               1999                        Dell
1        Rich Shapero               2004                     Too Far
2    MICHAEL CRICHTON               2000            Ballantine Books
3          Harper Lee               1988  Little Brown &amp; Company
4           Dan Brown               2001                 Pocket Star
..                ...                ...                         ...
109     J. K. Rowling               1999                  Scholastic
110     J. K. Rowling               2003                  Scholastic
111      John Grisham               1995     Dell Publishing Company
112   Janet Evanovich               1996                      Pocket
113    Nicholas Evans               1996                        Dell

                                              Synopsis
0    The Testament is a typical John Grisham novel...
1    Wild Animus tracks the reckless quest of Ranso...
2    While working at the site of an archaeological...
3    To Kill a Mockingbird novel by American author...
4    When Harvard symbologist Robert Langdon discov...
..                                                 ...
109  The plot follows Harry's second year at Hogwar...
110  During the summer Harry Potter is frustrated b...
111  Adam Hall an advocate and the grandson of Sam ...
112  Two for the Dough published in 1996 is the sec...
113  Annie's daughter Grace and their horse meet wi...

[114 rows x 6 columns]

In [92]:
# Step 2: Create User Profiles
merged_data = pd.merge(user_data, user_historical_view, on='userid')
print(merged_data)

    userid                 location   age        isbn
0    11676            n/a, n/a, n/a   NaN    60938455
1    11676            n/a, n/a, n/a   NaN   316096199
2    11676            n/a, n/a, n/a   NaN   316569321
3    11676            n/a, n/a, n/a   NaN   312195516
4    11676            n/a, n/a, n/a   NaN   345361792
..     ...                      ...   ...         ...
84  271448  ona, west virginia, usa  27.0  043935806X
85  271448  ona, west virginia, usa  27.0  044023722X
86  271448  ona, west virginia, usa  27.0   446672211
87  271448  ona, west virginia, usa  27.0   452282829
88  271448  ona, west virginia, usa  27.0   743237188

[89 rows x 4 columns]

In [93]:
user_book_data = pd.merge(merged_data, book_data[['isbn', 'Synopsis']], on='isbn')
print(user_book_data)

    userid                      location   age        isbn  \
0    11676                 n/a, n/a, n/a   NaN    60938455
1    11676                 n/a, n/a, n/a   NaN   316096199
2    11676                 n/a, n/a, n/a   NaN   316569321
3    11676                 n/a, n/a, n/a   NaN   312195516
4    35859        duluth, minnesota, usa   NaN   312195516
..     ...                           ...   ...         ...
84  204864  simi valley, california, usa  47.0   812550706
85  271448       ona, west virginia, usa  27.0    60928336
86  271448       ona, west virginia, usa  27.0   312291639
87  271448       ona, west virginia, usa  27.0  044023722X
88  271448       ona, west virginia, usa  27.0   743237188

                                             Synopsis
0   Fast Food Nation: The Dark Side of the All-Ame...
1   Lucky describes her experience of being raped ...
2   Powerfully acted adaptation of Janet Fitch's b...
3   Dinah opens the story by recounting for reader...
4   Dinah opens the story by recounting for reader...
..                                                ...
84  Ender's Game is a 1985 military science fictio...
85  A classic Southern tale of hilarious sadness s...
86  A college graduate gets employed as a nanny fo...
87  The story begins as Luke Chandler and his gran...
88  Set on stormy Cape Breton Island off Nova Scot...

[89 rows x 5 columns]

In [94]:
user_profiles = user_book_data.groupby('userid')['Synopsis'].apply(lambda x: ' '.join(map(str, x))).reset_index()
group_no = 10
user_profiles.to_csv(f'Part2_File1_Profile_Group[group_10].csv', index=False)

In [95]:
# Step 3: Vectorize the Book Synopses for Jaccard Similarity
vectorizer = CountVectorizer(binary=True, stop_words='english')
book_vectors = vectorizer.fit_transform(book_data['Synopsis'].fillna(''))

In [96]:
# Step 4: Calculate Jaccard Similarity Matrix
jaccard_sim_matrix = np.zeros((book_vectors.shape[0], book_vectors.shape[0]))

for i in range(book_vectors.shape[0]):
    for j in range(book_vectors.shape[0]):
        jaccard_sim_matrix[i, j] = jaccard_score(book_vectors.toarray()[i], book_vectors.toarray()[j])

/Users/waiphyooo/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Jaccard is ill-defined and being set to 0.0 due to no true or predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [97]:
# Convert to DataFrame for better handling
sim_matrix_df = pd.DataFrame(jaccard_sim_matrix, index=book_data['isbn'], columns=book_data['isbn'])

In [98]:
# Store the similarity matrix
sim_matrix_df.to_csv(f'Part2_File2_Model_Group[group_10].csv')

In [99]:
# Step 5: Recommend Top-10 Not-Yet-Read Books
recommendations = []
for user in user_data['userid']:
    read_books = user_historical_view[user_historical_view['userid'] == user]['isbn'].tolist()
    unread_books = [isbn for isbn in book_data['isbn'] if isbn not in read_books]

    user_recommendations = []
    for unread_book in unread_books:
        similarity_scores = sim_matrix_df.loc[unread_book, read_books]
        avg_similarity = similarity_scores.mean() if not similarity_scores.empty else 0
        user_recommendations.append((unread_book, avg_similarity))

    # Sort by similarity and pick the top 10
    top_10_books = sorted(user_recommendations, key=lambda x: x[1], reverse=True)[:10]
    
    for isbn, similarity in top_10_books:
        book_title = book_data.loc[book_data['isbn'] == isbn, 'booktitle'].values[0]
        recommendations.append({
            'User ID': user,
            'Book’s ISBN': isbn,
            'Book’s Title': book_title,
            'Jaccard Similarity': round(similarity, 3)
        })

In [100]:
# Store recommendations
recommendations_df = pd.DataFrame(recommendations)
recommendations_df.to_csv(f'Part2_File3_Recommendation_Group[group_10].csv', index=False)

In [101]:
# Display recommendations with spacing
print("Top 10 Recommendations for Each User:\n")
last_user_id = None
for _, row in recommendations_df.iterrows():
    if last_user_id and row['User ID'] != last_user_id:
        print()  # Add a blank line for separation
    print(f"User ID: {row['User ID']}")
    print(f"  Book’s ISBN: {row['Book’s ISBN']}")
    print(f"  Book’s Title: {row['Book’s Title']}")
    print(f"  Jaccard Similarity: {row['Jaccard Similarity']:.3f}")
    last_user_id = row['User ID']

Top 10 Recommendations for Each User:

User ID: 11676
  Book’s ISBN: 590353403
  Book’s Title: Harry Potter and the Sorcerer s Stone (Book 1)
  Jaccard Similarity: 0.078
User ID: 11676
  Book’s ISBN: 439064872
  Book’s Title: Harry Potter and the Chamber of Secrets (Book 2)
  Jaccard Similarity: 0.030
User ID: 11676
  Book’s ISBN: 804114986
  Book’s Title: The Bonesetter s Daughter
  Jaccard Similarity: 0.026
User ID: 11676
  Book’s ISBN: 439136369
  Book’s Title: Harry Potter and the Prisoner of Azkaban (Book 3)
  Jaccard Similarity: 0.024
User ID: 11676
  Book’s ISBN: 60987103
  Book’s Title: Wicked: The Life and Times of the Wicked Witch of the West
  Jaccard Similarity: 0.024
User ID: 11676
  Book’s ISBN: 684874350
  Book’s Title: ANGELA S ASHES
  Jaccard Similarity: 0.023
User ID: 11676
  Book’s ISBN: 671003755
  Book’s Title: She s Come Undone
  Jaccard Similarity: 0.021
User ID: 11676
  Book’s ISBN: 316776963
  Book’s Title: Me Talk Pretty One Day
  Jaccard Similarity: 0.020
User ID: 11676
  Book’s ISBN: 014028009X
  Book’s Title: Bridget Jones s Diary
  Jaccard Similarity: 0.020
User ID: 11676
  Book’s ISBN: 316284955
  Book’s Title: White Oleander : A Novel (Oprah s Book Club)
  Jaccard Similarity: 0.020

User ID: 16795
  Book’s ISBN: 671003755
  Book’s Title: She s Come Undone
  Jaccard Similarity: 0.026
User ID: 16795
  Book’s ISBN: 068484477X
  Book’s Title: STONES FROM THE RIVER
  Jaccard Similarity: 0.025
User ID: 16795
  Book’s ISBN: 142000205
  Book’s Title: Icy Sparks
  Jaccard Similarity: 0.021
User ID: 16795
  Book’s ISBN: 375726403
  Book’s Title: Empire Falls
  Jaccard Similarity: 0.021
User ID: 16795
  Book’s ISBN: 345361792
  Book’s Title: A Prayer for Owen Meany
  Jaccard Similarity: 0.021
User ID: 16795
  Book’s ISBN: 452282829
  Book’s Title: We Were the Mulvaneys
  Jaccard Similarity: 0.019
User ID: 16795
  Book’s ISBN: 440224764
  Book’s Title: The Partner
  Jaccard Similarity: 0.018
User ID: 16795
  Book’s ISBN: 375700757
  Book’s Title: Cold Mountain
  Jaccard Similarity: 0.018
User ID: 16795
  Book’s ISBN: 446310786
  Book’s Title: To Kill a Mockingbird
  Jaccard Similarity: 0.017
User ID: 16795
  Book’s ISBN: 316284955
  Book’s Title: White Oleander : A Novel (Oprah s Book Club)
  Jaccard Similarity: 0.017

User ID: 22625
  Book’s ISBN: 590353403
  Book’s Title: Harry Potter and the Sorcerer s Stone (Book 1)
  Jaccard Similarity: 0.108
User ID: 22625
  Book’s ISBN: 439064872
  Book’s Title: Harry Potter and the Chamber of Secrets (Book 2)
  Jaccard Similarity: 0.035
User ID: 22625
  Book’s ISBN: 439136369
  Book’s Title: Harry Potter and the Prisoner of Azkaban (Book 3)
  Jaccard Similarity: 0.028
User ID: 22625
  Book’s ISBN: 439139600
  Book’s Title: Harry Potter and the Goblet of Fire (Book 4)
  Jaccard Similarity: 0.026
User ID: 22625
  Book’s ISBN: 446608955
  Book’s Title: A Walk to Remember
  Jaccard Similarity: 0.021
User ID: 22625
  Book’s ISBN: 452282829
  Book’s Title: We Were the Mulvaneys
  Jaccard Similarity: 0.019
User ID: 22625
  Book’s ISBN: 439136350
  Book’s Title: Harry Potter and the Prisoner of Azkaban (Book 3)
  Jaccard Similarity: 0.019
User ID: 22625
  Book’s ISBN: 142001740
  Book’s Title: The Secret Life of Bees
  Jaccard Similarity: 0.018
User ID: 22625
  Book’s ISBN: 044021145X
  Book’s Title: The Firm
  Jaccard Similarity: 0.018
User ID: 22625
  Book’s ISBN: 786868716
  Book’s Title: The Five People You Meet in Heaven
  Jaccard Similarity: 0.017

User ID: 35859
  Book’s ISBN: 590353403
  Book’s Title: Harry Potter and the Sorcerer s Stone (Book 1)
  Jaccard Similarity: 0.174
User ID: 35859
  Book’s ISBN: 345361792
  Book’s Title: A Prayer for Owen Meany
  Jaccard Similarity: 0.036
User ID: 35859
  Book’s ISBN: 440213525
  Book’s Title: The Client
  Jaccard Similarity: 0.036
User ID: 35859
  Book’s ISBN: 452282829
  Book’s Title: We Were the Mulvaneys
  Jaccard Similarity: 0.031
User ID: 35859
  Book’s ISBN: 671003755
  Book’s Title: She s Come Undone
  Jaccard Similarity: 0.031
User ID: 35859
  Book’s ISBN: 142001740
  Book’s Title: The Secret Life of Bees
  Jaccard Similarity: 0.029
User ID: 35859
  Book’s ISBN: 684872153
  Book’s Title: Angela s Ashes (MMP) : A Memoir
  Jaccard Similarity: 0.028
User ID: 35859
  Book’s ISBN: 439064872
  Book’s Title: Harry Potter and the Chamber of Secrets (Book 2)
  Jaccard Similarity: 0.026
User ID: 35859
  Book’s ISBN: 345337662
  Book’s Title: Interview with the Vampire
  Jaccard Similarity: 0.025
User ID: 35859
  Book’s ISBN: 316769487
  Book’s Title: The Catcher in the Rye
  Jaccard Similarity: 0.024

User ID: 95359
  Book’s ISBN: 804114986
  Book’s Title: The Bonesetter s Daughter
  Jaccard Similarity: 0.044
User ID: 95359
  Book’s ISBN: 60987103
  Book’s Title: Wicked: The Life and Times of the Wicked Witch of the West
  Jaccard Similarity: 0.037
User ID: 95359
  Book’s ISBN: 380789035
  Book’s Title: American Gods
  Jaccard Similarity: 0.035
User ID: 95359
  Book’s ISBN: 380789019
  Book’s Title: Neverwhere
  Jaccard Similarity: 0.033
User ID: 95359
  Book’s ISBN: 684874350
  Book’s Title: ANGELA S ASHES
  Jaccard Similarity: 0.032
User ID: 95359
  Book’s ISBN: 345337662
  Book’s Title: Interview with the Vampire
  Jaccard Similarity: 0.027
User ID: 95359
  Book’s ISBN: 671021001
  Book’s Title: She s Come Undone
  Jaccard Similarity: 0.026
User ID: 95359
  Book’s ISBN: 60915544
  Book’s Title: The Bean Trees
  Jaccard Similarity: 0.023
User ID: 95359
  Book’s ISBN: 786868716
  Book’s Title: The Five People You Meet in Heaven
  Jaccard Similarity: 0.023
User ID: 95359
  Book’s ISBN: 316284955
  Book’s Title: White Oleander : A Novel (Oprah s Book Club)
  Jaccard Similarity: 0.022

User ID: 104636
  Book’s ISBN: 590353403
  Book’s Title: Harry Potter and the Sorcerer s Stone (Book 1)
  Jaccard Similarity: 0.146
User ID: 104636
  Book’s ISBN: 439136350
  Book’s Title: Harry Potter and the Prisoner of Azkaban (Book 3)
  Jaccard Similarity: 0.049
User ID: 104636
  Book’s ISBN: 439064864
  Book’s Title: Harry Potter and the Chamber of Secrets (Book 2)
  Jaccard Similarity: 0.047
User ID: 104636
  Book’s ISBN: 043935806X
  Book’s Title: Harry Potter and the Order of the Phoenix (Book 5)
  Jaccard Similarity: 0.032
User ID: 104636
  Book’s ISBN: 345361792
  Book’s Title: A Prayer for Owen Meany
  Jaccard Similarity: 0.027
User ID: 104636
  Book’s ISBN: 440213525
  Book’s Title: The Client
  Jaccard Similarity: 0.023
User ID: 104636
  Book’s ISBN: 446608955
  Book’s Title: A Walk to Remember
  Jaccard Similarity: 0.020
User ID: 104636
  Book’s ISBN: 316769487
  Book’s Title: The Catcher in the Rye
  Jaccard Similarity: 0.019
User ID: 104636
  Book’s ISBN: 452282829
  Book’s Title: We Were the Mulvaneys
  Jaccard Similarity: 0.016
User ID: 104636
  Book’s ISBN: 60987103
  Book’s Title: Wicked: The Life and Times of the Wicked Witch of the West
  Jaccard Similarity: 0.016

User ID: 110912
  Book’s ISBN: 60987103
  Book’s Title: Wicked: The Life and Times of the Wicked Witch of the West
  Jaccard Similarity: 0.042
User ID: 110912
  Book’s ISBN: 380789035
  Book’s Title: American Gods
  Jaccard Similarity: 0.034
User ID: 110912
  Book’s ISBN: 671003755
  Book’s Title: She s Come Undone
  Jaccard Similarity: 0.033
User ID: 110912
  Book’s ISBN: 345337662
  Book’s Title: Interview with the Vampire
  Jaccard Similarity: 0.032
User ID: 110912
  Book’s ISBN: 439064872
  Book’s Title: Harry Potter and the Chamber of Secrets (Book 2)
  Jaccard Similarity: 0.031
User ID: 110912
  Book’s ISBN: 684874350
  Book’s Title: ANGELA S ASHES
  Jaccard Similarity: 0.028
User ID: 110912
  Book’s ISBN: 60915544
  Book’s Title: The Bean Trees
  Jaccard Similarity: 0.028
User ID: 110912
  Book’s ISBN: 439136350
  Book’s Title: Harry Potter and the Prisoner of Azkaban (Book 3)
  Jaccard Similarity: 0.028
User ID: 110912
  Book’s ISBN: 449212602
  Book’s Title: The Handmaid s Tale
  Jaccard Similarity: 0.026
User ID: 110912
  Book’s ISBN: 446310786
  Book’s Title: To Kill a Mockingbird
  Jaccard Similarity: 0.026

User ID: 204864
  Book’s ISBN: 684872153
  Book’s Title: Angela s Ashes (MMP) : A Memoir
  Jaccard Similarity: 0.041
User ID: 204864
  Book’s ISBN: 804114986
  Book’s Title: The Bonesetter s Daughter
  Jaccard Similarity: 0.034
User ID: 204864
  Book’s ISBN: 60392452
  Book’s Title: Stupid White Men ...and Other Sorry Excuses for the State of the Nation!
  Jaccard Similarity: 0.027
User ID: 204864
  Book’s ISBN: 60987103
  Book’s Title: Wicked: The Life and Times of the Wicked Witch of the West
  Jaccard Similarity: 0.025
User ID: 204864
  Book’s ISBN: 345337662
  Book’s Title: Interview with the Vampire
  Jaccard Similarity: 0.025
User ID: 204864
  Book’s ISBN: 142001740
  Book’s Title: The Secret Life of Bees
  Jaccard Similarity: 0.025
User ID: 204864
  Book’s ISBN: 345361792
  Book’s Title: A Prayer for Owen Meany
  Jaccard Similarity: 0.024
User ID: 204864
  Book’s ISBN: 553572997
  Book’s Title: The Alienist
  Jaccard Similarity: 0.023
User ID: 204864
  Book’s ISBN: 446310786
  Book’s Title: To Kill a Mockingbird
  Jaccard Similarity: 0.022
User ID: 204864
  Book’s ISBN: 60915544
  Book’s Title: The Bean Trees
  Jaccard Similarity: 0.021

User ID: 271448
  Book’s ISBN: 312278586
  Book’s Title: The Nanny Diaries
  Jaccard Similarity: 0.125
User ID: 271448
  Book’s ISBN: 439136369
  Book’s Title: Harry Potter and the Prisoner of Azkaban (Book 3)
  Jaccard Similarity: 0.034
User ID: 271448
  Book’s ISBN: 375726403
  Book’s Title: Empire Falls
  Jaccard Similarity: 0.028
User ID: 271448
  Book’s ISBN: 684872153
  Book’s Title: Angela s Ashes (MMP) : A Memoir
  Jaccard Similarity: 0.026
User ID: 271448
  Book’s ISBN: 375727345
  Book’s Title: House of Sand and Fog
  Jaccard Similarity: 0.025
User ID: 271448
  Book’s ISBN: 590353403
  Book’s Title: Harry Potter and the Sorcerer s Stone (Book 1)
  Jaccard Similarity: 0.025
User ID: 271448
  Book’s ISBN: 059035342X
  Book’s Title: Harry Potter and the Sorcerer s Stone (Harry Potter (Paperback))
  Jaccard Similarity: 0.025
User ID: 271448
  Book’s ISBN: 142001740
  Book’s Title: The Secret Life of Bees
  Jaccard Similarity: 0.020
User ID: 271448
  Book’s ISBN: 312195516
  Book’s Title: The Red Tent (Bestselling Backlist)
  Jaccard Similarity: 0.020
User ID: 271448
  Book’s ISBN: 375700757
  Book’s Title: Cold Mountain
  Jaccard Similarity: 0.020

In [102]:
import pandas as pd
 
# Load data
recommendations_df = pd.read_csv('Part2_File3_Recommendation_Groupgroup_10.csv')
test_user_answers = pd.read_csv('TestUserAnswers.csv')

In [103]:
recommendations_df.head()

,User ID,Book’s ISBN,Book’s Title,Jaccard Similarity
0,11676,590353403,Harry Potter and the Sorcerer s Stone (Book 1),0.078
1,11676,439064872,Harry Potter and the Chamber of Secrets (Book 2),0.030
2,11676,804114986,The Bonesetter s Daughter,0.026
3,11676,439136369,Harry Potter and the Prisoner of Azkaban (Book 3),0.024
4,11676,60987103,Wicked: The Life and Times of the Wicked Witch...,0.024

In [104]:
test_user_answers.head()

   userid        isbn
0   11676    60502258
1   11676    60987103
2   11676    61009059
3   11676  014028009X
4   11676   142000205

In [105]:
# Calculate Precision, Recall, and F-measure
evaluation_results = []
 
for user_id in test_user_answers['userid'].unique():
    # Get recommended books for the user
    recommended_books = recommendations_df[recommendations_df['User ID'] == user_id]['Book’s ISBN'].tolist()
    # Get relevant books from the test dataset
    relevant_books = test_user_answers[test_user_answers['userid'] == user_id]['isbn'].tolist()
    # Calculate 'a' - number of relevant books in the top 10 recommendations
    a = len(set(recommended_books) & set(relevant_books))
    # Total relevant items for the user in the test dataset
    total_relevant_items = len(relevant_books)
    # Precision, Recall, and F-measure
    precision = a / 90
    recall = a / total_relevant_items if total_relevant_items > 0 else 0
    f_measure = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    # Append results
    evaluation_results.append({
        'User ID': user_id,
        'Precision': precision,
        'Recall': recall,
        'F-measure': f_measure
    })

In [107]:
# Convert results to DataFrame
evaluation_df = pd.DataFrame(evaluation_results)
print(evaluation_df)
# Save the evaluation metrics to a CSV file
evaluation_df.to_csv('Part2_File4_Evaluation_Group[group_10].csv', index=False)

   User ID  Precision    Recall  F-measure
0    11676   0.088889  0.170213   0.116788
1    16795   0.022222  0.074074   0.034188
2    22625   0.033333  0.428571   0.061856
3    35859   0.011111  0.076923   0.019417
4    95359   0.022222  0.090909   0.035714
5   104636   0.011111  0.066667   0.019048
6   110912   0.022222  0.222222   0.040404
7   204864   0.011111  0.100000   0.020000
8   271448   0.022222  0.181818   0.039604